/**
 * @fileoverview Constants for the linked-package watcher
 */

/**
 * Name of the trigger file that gets touched to trigger webpack recompilation
 * @constant {string}
 */
const TRIGGER_FILE_NAME = '.symlink-trigger.js';

/**
 * Content for the trigger file (exports a timestamp)
 * @constant {string}
 */
const TRIGGER_FILE_CONTENT = `// Auto-generated by nice-toolkit --watch
// This file is touched when linked packages change to trigger recompilation
// Add this file to .gitignore
export const SYMLINK_TRIGGER_TIMESTAMP = `;

/**
 * Debounce delay in milliseconds
 * @constant {number}
 */
const DEBOUNCE_DELAY = 300;

module.exports = {
  TRIGGER_FILE_NAME,
  TRIGGER_FILE_CONTENT,
  DEBOUNCE_DELAY,
};
